# Generated by Django 5.0.3 on 2024-04-18 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=55)),
                ('member_email', models.EmailField(max_length=50)),
                ('member_role', models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee')], default='Employee', max_length=55)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
            ],
        ),
    ]
