# Generated by Django 5.0.3 on 2024-04-18 11:04

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_project_client_remove_member_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=55)),
                ('client_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('client_status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='Active', max_length=55)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.company')),
            ],
        ),
    ]
